name: meta_weather_api
description: A Dart API Client for the MetaWeather API.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  mocktail: ^0.1.0
  test: ^1.16.4
