name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.3.0
  meta_weather_api:
    path: ../meta_weather_api

dev_dependencies:
  coverage: ^1.0.3
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  mocktail: ^0.1.0
  test: ^1.16.4
